export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transcation with zero fees',
    description: 'Get acces to our exclusive app that allow you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: '/images/svg-1.svg',
    alt: 'car',
    light: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Virtual Card',
    headline: 'No need to wait for a card to arrive',
    description: 'Start spending online or in-store immediately using a virtual card',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: '/images/svg-2.svg',
    alt: 'virtual-card',
    light: true,
    primary: true,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Join our Team',
    headline: 'Creating an account is extreamly easy',
    description: 'Get everything set up and ready in undrer 10 minutes.',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: '/images/svg-3.svg',
    alt: 'signup',
    light: true,
    primary: true,
    darkText: true,
};